# 1. yaml格式的文件, 也是使用#来添加注释
# 2. 每一个区域下的选项缩进要一致, 推荐缩进两个空格
excel:
    cases_path: "cases.xlsx"
    result_col: 8
    actual_col: 7
msg:
  success_result: Success
  fail_result: Fail
log:
  log_name: cases
  logger_level: DEBUG
  formatter: '%(asctime)s - [%(filename)s-->line:%(lineno)d] - %(levelname)s: %(message)s'
  stream_level: DEBUG
  logfile_name: test.log
  logfile_level: DEBUG
report:
  name: report
  title: "自动化测试23期的优秀报告"
  description: "这是一个美轮美奂的报告"
  tester: "少艾"
mysql:
  host: 'localhost'
  user: 'root'
  password: 'root'
  db: 'jmeter_class'
  port: 3306
  select_demo_sql: "SELECT * FROM jmeter_class.user where 1= %s;"
api:
  version: {"X-Lemonban-Media-Type": "lemonban.v2"}
  host: "http://api.lemonban.com/futureloan"