# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver


class TestLinkText():
  #初始化
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.get("https://testerhome.com/")
  #方法执行完成后执行
  def teardown_method(self, method):
    self.driver.quit()

  def test_linktext(self):
    self.driver.set_window_size(1390, 877)
    self.driver.find_element_by_link_text("STF 集成 iOS 之 开源了").click()
    time.sleep(5)
    self.driver.find_element_by_link_text("https://github.com/mrx1203/WebDriverAgent.git").click()
    time.sleep(5)

    handles = self.driver.window_handles

    # 当前句柄与最新窗口不一致时，将当前句柄切换为最新窗口句柄
    if handles[-1] != self.driver.current_window_handle:
      self.driver.switch_to.window(handles[-1])

    assert "A WebDriver server for iOS that runs inside the Simulator" in self.driver.page_source

  
